/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2024-05-19 07:55:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/OneDrive%20-%20University%20of%20Technology%20and%20Education/Desktop/BaiTapTHJVA/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cafe/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1716082008645L));
    _jspx_dependants.put("jar:file:/D:/OneDrive%20-%20University%20of%20Technology%20and%20Education/Desktop/BaiTapTHJVA/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cafe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710262135216L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710436164282L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Trang chủ</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     <!-- Carousel Start -->\r\n");
      out.write("    <div class=\"container-fluid p-0 mb-5\">\r\n");
      out.write("        <div id=\"blog-carousel\" class=\"carousel slide overlay-bottom\" data-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"template/web/img/carousel-1.jpg\" alt=\"Image\">\r\n");
      out.write("                    <div class=\"carousel-caption d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("                        <h2 class=\"text-primary font-weight-medium m-0\">Chúng tôi đã và đang phục vụ</h2>\r\n");
      out.write("                        <h1 class=\"display-1 text-white m-0\">Các loại đồ uống</h1>\r\n");
      out.write("                        <h2 class=\"text-white m-0\">* kể từ  2020 *</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"template/web/img/carousel-2.jpg\" alt=\"Image\">\r\n");
      out.write("                    <div class=\"carousel-caption d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("                        <h2 class=\"text-primary font-weight-medium m-0\">Chúng tôi đã và đang phục vụ</h2>\r\n");
      out.write("                        <h1 class=\"display-1 text-white m-0\">Các loại đồ uống</h1>\r\n");
      out.write("                        <h2 class=\"text-white m-0\">* kể từ  2020 *</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"carousel-control-prev\" href=\"#blog-carousel\" data-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"carousel-control-next\" href=\"#blog-carousel\" data-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Carousel End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- About Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-title\">\r\n");
      out.write("                <h4 class=\"text-primary text-uppercase\" style=\"letter-spacing: 5px;\">Giới thiệu chung</h4>\r\n");
      out.write("                <h1 class=\"display-4\"></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 py-0 py-lg-5\">\r\n");
      out.write("                    <h1 class=\"mb-3\">Câu chuyện</h1>\r\n");
      out.write("                    <h5 class=\"mb-3\">Chào mừng bạn đến với quán nước của chúng tôi, nơi không chỉ phục vụ những ly nước tươi mát mà còn mang đến không gian thân thiện và thư giãn.</h5>\r\n");
      out.write("                    <p> Nơi đây còn là điểm hẹn lý tưởng để tụ họp, chia sẻ những khoảnh khắc vui vẻ và tận hưởng hương vị độc đáo của cuộc sống.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <a href=\"\" class=\"btn btn-secondary font-weight-bold py-2 px-4 mt-2\">Xem thêm</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 py-5 py-lg-0\" style=\"min-height: 500px;\">\r\n");
      out.write("                    <div class=\"position-relative h-100\">\r\n");
      out.write("                        <img class=\"position-absolute w-100 h-100\" src=\"template/web/img/about.png\" style=\"object-fit: cover;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 py-0 py-lg-5\">\r\n");
      out.write("                    <h1 class=\"mb-3\">Tầm nhìn</h1>\r\n");
      out.write("                    <p> Trở thành điểm đến hàng đầu, mang đến những trải nghiệm nước uống tinh tế và không gian thư giãn, thân thiện với nguyên liệu tươi ngon và sáng tạo trong pha chế.</p>\r\n");
      out.write("                    <h5 class=\"mb-3\"><i class=\"fa fa-check text-primary mr-3\"></i>Đảm bảo chất lượng và an toàn thực phẩm trong từng ly nước.</h5>\r\n");
      out.write("                    <h5 class=\"mb-3\"><i class=\"fa fa-check text-primary mr-3\"></i>Tạo nên một cộng đồng gắn kết và thân thiện.</h5>\r\n");
      out.write("                    <h5 class=\"mb-3\"><i class=\"fa fa-check text-primary mr-3\"></i>Đổi mới liên tục để đáp ứng nhu cầu và sở thích đa dạng của khách hàng.</h5>\r\n");
      out.write("                    <a href=\"\" class=\"btn btn-primary font-weight-bold py-2 px-4 mt-2\">Xem thêm</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- About End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Service Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-title\">\r\n");
      out.write("                <h4 class=\"text-primary text-uppercase\" style=\"letter-spacing: 5px;\">Dịch vụ của chúng tôi</h4>\r\n");
      out.write("                <h1 class=\"display-4\"></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-6 mb-5\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"col-sm-5\">\r\n");
      out.write("                            <img class=\"img-fluid mb-3 mb-sm-0\" src=\"template/web/img/service-1.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-7\">\r\n");
      out.write("                            <h4><i class=\"fa fa-truck service-icon\"></i>Giao hàng tận nơi nhanh nhất</h4>\r\n");
      out.write("                            <p class=\"m-0\">Trải nghiệm dịch vụ giao hàng tận nơi tiện lợi của chúng tôi, mang những ly nước tươi ngon đến thẳng cửa nhà bạn!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 mb-5\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"col-sm-5\">\r\n");
      out.write("                            <img class=\"img-fluid mb-3 mb-sm-0\" src=\"template/web/img/nguyenlieu.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-7\">\r\n");
      out.write("                            <h4><i class=\"fa fa-coffee service-icon\"></i>Nguyên liệu trái cây tươi ngon</h4>\r\n");
      out.write("                            <p class=\"m-0\">Chúng tôi tự hào sử dụng những nguyên liệu trái cây tươi ngon nhất, đảm bảo mang đến hương vị tự nhiên và dinh dưỡng tốt nhất cho mỗi ly nước uống tại quán.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 mb-5\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"col-sm-5\">\r\n");
      out.write("                            <img class=\"img-fluid mb-3 mb-sm-0\" src=\"template/web/img/service-3.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-7\">\r\n");
      out.write("                            <h4><i class=\"fa fa-award service-icon\"></i>Cà phê chất lượng tốt nhất</h4>\r\n");
      out.write("                            <p class=\"m-0\">Cà phê chất lượng cao, được chăm sóc kỹ lưỡng từ việc chọn lựa nguyên liệu đến quá trình pha chế, mang lại trải nghiệm thưởng thức tinh tế và đầy hứng khởi cho mỗi khách hàng.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 mb-5\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"col-sm-5\">\r\n");
      out.write("                            <img class=\"img-fluid mb-3 mb-sm-0\" src=\"template/web/img/service-4.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-7\">\r\n");
      out.write("                            <h4><i class=\"fa fa-table service-icon\"></i>Đặt bàn online</h4>\r\n");
      out.write("                            <p class=\"m-0\">Đặt bàn online dễ dàng và tiện lợi, mang lại trải nghiệm đẳng cấp và không gian thưởng thức nước uống tốt nhất tại quán của chúng tôi.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Service End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Offer Start -->\r\n");
      out.write("    <div class=\"offer container-fluid my-5 py-5 text-center position-relative overlay-top overlay-bottom\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <h1 class=\"display-3 text-primary mt-3\">Giảm 50%</h1>\r\n");
      out.write("            <h1 class=\"text-white mb-3\">Ưu đãi đặc biệt ngày chủ nhật</h1>\r\n");
      out.write("            <h4 class=\"text-white font-weight-normal mb-4 pb-3\">Chỉ ưu đãi chủ nhật từ ngày 1 đến ngày 21 tháng 6 </h4>\r\n");
      out.write("            <form class=\"form-inline justify-content-center mb-4\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control p-4\" placeholder=\"Email\" style=\"height: 60px;\">\r\n");
      out.write("                    <div class=\"input-group-append\">\r\n");
      out.write("                        <button class=\"btn btn-primary font-weight-bold px-4\" type=\"submit\">Đăng ký</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Offer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Menu Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-title\">\r\n");
      out.write("                <h4 class=\"text-primary text-uppercase\" style=\"letter-spacing: 5px;\">Thực đơn và giá cả</h4>\r\n");
      out.write("                <h1 class=\"display-4\">Giá cả cạnh tranh</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <h1 class=\"mb-5\">Đồ uống nóng</h1>\r\n");
      out.write("                    <div class=\"row align-items-center mb-5\">\r\n");
      out.write("                        <div class=\"col-4 col-sm-3\">\r\n");
      out.write("                            <img class=\"w-100 rounded-circle mb-3 mb-sm-0\" src=\"img/tragung.png\" alt=\"\">\r\n");
      out.write("                            <h5 class=\"menu-price\">$5</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-8 col-sm-9\">\r\n");
      out.write("                            <h4>Trà gừng</h4>\r\n");
      out.write("                            <p class=\"m-0\">Hương vị gừng đặc trưng hoà quyện trong hơi nóng, mang đến cảm giác sảng khoái và bổ dưỡng cho mỗi ngụm uống.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row align-items-center mb-5\">\r\n");
      out.write("                        <div class=\"col-4 col-sm-3\">\r\n");
      out.write("                            <img class=\"w-100 rounded-circle mb-3 mb-sm-0\" src=\"img/suanong.jpg\" alt=\"\">\r\n");
      out.write("                            <h5 class=\"menu-price\">$7</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-8 col-sm-9\">\r\n");
      out.write("                            <h4>Sữa </h4>\r\n");
      out.write("                            <p class=\"m-0\">Sữa nóng đầy dinh dưỡng là lựa chọn hoàn hảo để tăng cường sức khỏe và cảm giác ấm áp cho bạn.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row align-items-center mb-5\">\r\n");
      out.write("                        <div class=\"col-4 col-sm-3\">\r\n");
      out.write("                            <img class=\"w-100 rounded-circle mb-3 mb-sm-0\" src=\"img/menu-3.jpg\" alt=\"\">\r\n");
      out.write("                            <h5 class=\"menu-price\">$9</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-8 col-sm-9\">\r\n");
      out.write("                            <h4>Cà phê sữa</h4>\r\n");
      out.write("                            <p class=\"m-0\">Sự kết hợp giữa sữa và cà phê mang lại hương vị đậm đà và ngọt ngào.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <h1 class=\"mb-5\">Đồ uống lạnh</h1>\r\n");
      out.write("                    <div class=\"row align-items-center mb-5\">\r\n");
      out.write("                        <div class=\"col-4 col-sm-3\">\r\n");
      out.write("                            <img class=\"w-100 rounded-circle mb-3 mb-sm-0\" src=\"img/trachanh.avif\" alt=\"\">\r\n");
      out.write("                            <h5 class=\"menu-price\">$5</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-8 col-sm-9\">\r\n");
      out.write("                            <h4>Nước chanh</h4>\r\n");
      out.write("                            <p class=\"m-0\">Nước chanh tươi ngon, giải nhiệt mùa hè.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row align-items-center mb-5\">\r\n");
      out.write("                        <div class=\"col-4 col-sm-3\">\r\n");
      out.write("                            <img class=\"w-100 rounded-circle mb-3 mb-sm-0\" src=\"img/nuoccam.jpg\" alt=\"\">\r\n");
      out.write("                            <h5 class=\"menu-price\">$7</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-8 col-sm-9\">\r\n");
      out.write("                            <h4>Nước cam</h4>\r\n");
      out.write("                            <p class=\"m-0\">Nước cam nguyên chất là nguồn cung cấp vitamin C tự nhiên và hương vị tươi mát.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row align-items-center mb-5\">\r\n");
      out.write("                        <div class=\"col-4 col-sm-3\">\r\n");
      out.write("                            <img class=\"w-100 rounded-circle mb-3 mb-sm-0\" src=\"img/sinhto.jpg\" alt=\"\">\r\n");
      out.write("                            <h5 class=\"menu-price\">$9</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-8 col-sm-9\">\r\n");
      out.write("                            <h4>Sinh tố</h4>\r\n");
      out.write("                            <p class=\"m-0\">Sự kết hợp đa dạng của nhiều loại trái cây đầy dinh dưỡng và  tươi mát.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Menu End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Reservation Start -->\r\n");
      out.write("    <div class=\"container-fluid my-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"reservation position-relative overlay-top overlay-bottom\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-6 my-5 my-lg-0\">\r\n");
      out.write("                        <div class=\"p-5\">\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <h1 class=\"display-3 text-primary\">Giảm 30%</h1>\r\n");
      out.write("                                <h1 class=\"text-white\">Đặt bàn online</h1>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"text-white\">Khi bạn đặt bàn trực tuyến tại quán nước của chúng tôi, bạn sẽ nhận được ưu đãi giảm giá hấp dẫn:</p>\r\n");
      out.write("                            <ul class=\"list-inline text-white m-0\">\r\n");
      out.write("                                <li class=\"py-2\"><i class=\"fa fa-check text-primary mr-3\"></i>Tiết kiệm 10% cho tất cả các loại nước uống.</li>\r\n");
      out.write("                                <li class=\"py-2\"><i class=\"fa fa-check text-primary mr-3\"></i>Nhận thêm phiếu giảm giá 20% cho lần ghé thăm tiếp theo.</li>\r\n");
      out.write("                                <li class=\"py-2\"><i class=\"fa fa-check text-primary mr-3\"></i>Miễn phí món tráng miệng cho nhóm từ 4 người trở lên.</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"text-center p-5\" style=\"background: rgba(51, 33, 29, .8);\">\r\n");
      out.write("                            <h1 class=\"text-white mb-4 mt-5\">Đặt bàn</h1>\r\n");
      out.write("                            <form class=\"mb-5\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control bg-transparent border-primary p-4\" placeholder=\"Tên\"\r\n");
      out.write("                                        required=\"required\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"email\" class=\"form-control bg-transparent border-primary p-4\" placeholder=\"Email\"\r\n");
      out.write("                                        required=\"required\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <div class=\"date\" id=\"date\" data-target-input=\"nearest\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control bg-transparent border-primary p-4 datetimepicker-input\" placeholder=\"Ngày\" data-target=\"#date\" data-toggle=\"datetimepicker\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <div class=\"time\" id=\"time\" data-target-input=\"nearest\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control bg-transparent border-primary p-4 datetimepicker-input\" placeholder=\"Giờ\" data-target=\"#time\" data-toggle=\"datetimepicker\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <select class=\"custom-select bg-transparent border-primary px-4\" style=\"height: 49px;\">\r\n");
      out.write("                                        <option selected>số người</option>\r\n");
      out.write("                                        <option value=\"1\">1 người</option>\r\n");
      out.write("                                        <option value=\"2\">2 người </option>\r\n");
      out.write("                                        <option value=\"3\">3 người/option>\r\n");
      out.write("                                        <option value=\"3\">4 người</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-block font-weight-bold py-3\" type=\"submit\">Đặt ngay</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Reservation End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Testimonial Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-title\">\r\n");
      out.write("                <h4 class=\"text-primary text-uppercase\" style=\"letter-spacing: 5px;\">Đánh giá</h4>\r\n");
      out.write("                <h1 class=\"display-4\">Đánh giá của khách hàng</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"owl-carousel testimonial-carousel\">\r\n");
      out.write("                <div class=\"testimonial-item\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"template/web/img/testimonial-1.jpg\" alt=\"\">\r\n");
      out.write("                        <div class=\"ml-3\">\r\n");
      out.write("                            <h4>David Wilson</h4>\r\n");
      out.write("                            <i>Kiến trúc sư</i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"m-0\">Menu đa dạng và chất lượng nước uống tuyệt hảo. Tôi đặc biệt thích dịch vụ giao hàng nhanh chóng của quán, luôn nhận được nước uống tươi ngon ngay tại nhà.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"testimonial-item\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"template/web/img/testimonial-2.jpg\" alt=\"\">\r\n");
      out.write("                        <div class=\"ml-3\">\r\n");
      out.write("                            <h4>Sarah Brown</h4>\r\n");
      out.write("                            <i>Giáo viên</i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"m-0\">Quán nước này là nơi lý tưởng để thư giãn. Không gian thoải mái và nhân viên rất nhiệt tình. Dịch vụ giao hàng tận nơi cũng rất nhanh và tiện lợi.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"testimonial-item\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"template/web/img/testimonial-3.jpg\" alt=\"\">\r\n");
      out.write("                        <div class=\"ml-3\">\r\n");
      out.write("                            <h4>Michael Smith</h4>\r\n");
      out.write("                            <i>Luật sư</i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"m-0\">Tôi rất ấn tượng với chất lượng nước uống ở đây. Nguyên liệu tươi ngon và pha chế sáng tạo. Dịch vụ giao hàng rất đúng giờ, tôi sẽ quay lại nhiều lần</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"testimonial-item\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"template/web/img/testimonial-4.jpg\" alt=\"\">\r\n");
      out.write("                        <div class=\"ml-3\">\r\n");
      out.write("                            <h4>Emily </h4>\r\n");
      out.write("                            <i>Bác sĩ</i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"m-0\">Thức uống tại quán thật tuyệt vời! Mỗi ly nước đều tươi mát và đầy hương vị. Dịch vụ giao hàng nhanh chóng và thân thiện nữa</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Testimonial End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
